### model
model_name_or_path: ./model/DeepSeek-R1-Distill-Llama-8B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj

### ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_offload_config.json


### dataset
dataset: wyckoff_element_form_train
template: llama3
cutoff_len: 1024
max_samples: 130000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./LLaMA-Factory/saves/r1_wyckoff_element_form
logging_steps: 20
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_total_limit: 1000000

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: false

### eval
val_size: 0.111111111111111111111111111111111
per_device_eval_batch_size: 8
evaluation_strategy: steps
eval_steps: 500