cutoff_len: 1024
dataset: wyckoff_element_gap_train
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_offload_config.json
do_train: true
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
fp16: false
gradient_accumulation_steps: 8
learning_rate: 0.0001
logging_steps: 20
lora_target: q_proj,k_proj,v_proj
lr_scheduler_type: cosine
max_samples: 130000
model_name_or_path: ./model/Meta-Llama-3.1-8B-Instruct
num_train_epochs: 20.0
output_dir: ./LLaMA-Factory/saves/llama_wyckoff_element_gap
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
save_steps: 500
save_total_limit: 1000000
stage: sft
template: llama3
val_size: 0.1111111111111111
warmup_ratio: 0.1
